services:
  jaeger:
    image: jaegertracing/all-in-one
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    expose:
      - "9411"
      - "16686"
    ports:
      - "9411:9411"
      - "16686:16686"
  authorization:
    build: authorization
    ports:
      - 7000:8080
  customer:
    build: customer
    ports:
      - 7001:8080
  offer: 
    build: offer
    ports:
      - 7002:8080 
  ui:
    build: ui
    configs: 
       - source: nginx_config
         target: /etc/nginx/nginx.conf:ro

    ports:
     - 8001:80
  opa:
    image: openpolicyagent/opa
    command: ["run", "--server", "--set=decision_logs.console=true"]
    ports:
     - "8181:8181"
 
configs:
  nginx_config:
    file: ./reverse-proxy/nginx.conf